name: CI

on: [push]

jobs:
  build-and-test:
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.11.0
        uses: actions/setup-node@v1
        with:
          node-version: 16.11.0
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: node_modules-v1-${{ hashFiles('yarn.lock') }}
          # loading an older version is fine here, since it will get an npm install
          restore-keys: |
            node_modules-

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - run: yarn format-check

      - run: yarn lint
